### ISSUE TITLE
Updated website

### ISSUE THREAD

**Issue by ciolt** [PrismarineJS/prismarinejs.github.io#12]
Hey guys, I recently stumbled back upon the PrismarineJS website and realized it needed some updating to a more modern look -- as well as some adjustments for more maintainability. For example, having a build system based on Pug templates and Sass. I also added some SEO stuff such as more descriptive metadata in the head for higher rankings on Google and Bing.

![image](https://user-images.githubusercontent.com/5000732/35658898-8494516a-06d1-11e8-9d38-f6a3a52200dd.png)

It's also fully responsive now. Which means higher rankings on Google. That means more people get involved.

![image](https://user-images.githubusercontent.com/5000732/35659162-c6aca75e-06d2-11e8-9936-0459af00a471.png)

### The Issue

The site isn't publishing correctly since the repo is set to publish GitHub pages from `master`. I need it to be set to `gh-pages` in the settings page to make the new Gulp build system work.

**Comment by roblabla** [comment]
🤔 I can't make it point to gh-pages for some reason. It says "User pages must be built from the master branch.".

**Comment by roblabla** [comment]
Maybe you should have the source live in the "source" branch, and have gulp publish to master ?

**Comment by ciolt** [comment]
Thanks, I'll see what I can do.
