### ISSUE TITLE
Obtain prismarine.js.org domain

### ISSUE THREAD

**Issue by mhsjlw** [PrismarineJS/prismarinejs.github.io#14]
I'm following the guide @ https://dns.js.org/ 

This issue will be updated with PRs and issues, etc.

**Comment by mhsjlw** [comment]
https://github.com/PrismarineJS/prismarinejs.github.io/pull/15

**Comment by rom1504** [comment]
cool

**Comment by mhsjlw** [comment]
https://prismarine.js.org

**Comment by dcbartlett** [comment]
nice
