### ISSUE TITLE
Update this site to fit to new PrismarineJS things

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarinejs.github.io#6]
Relatively to https://github.com/PrismarineJS/flying-squid

**Comment by rom1504** [comment]
lot of people ask what's PrismarineJS.
Here is a recent answer about it:

> 00:37 < rom1504> PrismarineJS is mostly a lot of modules about mc+node.js
> 00:37 < rom1504> used both in mineflayer (client) and flying-squid (server)
> 00:37 < rom1504> and in other stuff (proxy, schematic reader,...)

would be useful to put something like that somewhere easy to see for new comers

**Comment by BradyLF** [comment]
Added the description and the new development members not previously on the site

**Comment by rom1504** [comment]
Ah thanks for doing this.
I guess I'll add some more details later since this was just a quick answer copy pasted from gitter.

**Comment by BradyLF** [comment]
No problem! Yeah I just copied it because I wasn't sure what else to write, and didn't want to incorrectly define the project. Please add any more issues if you notice anything incorrect. Also, terribly sorry the code is such a mess, built this site rather hastily the first time round :P
